# A functional, but probably terrible, example of GitLab CI for Flutter
image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "28.0.3"
  ANDROID_SDK_TOOLS: "26.1.1"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet --yes install locales
  - sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - apt-get install libglu1-mesa
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter channel beta
  - ./flutter/bin/flutter doctor
  - ls $ANDROID_HOME

stages:
  - build
  - package


build:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script:
    - ./flutter/bin/flutter build apk
  artifacts:
    paths:
    - build/app/outputs/


.package_template: &package
  before_script:
    - mkdir -p exported

package:
  <<: *package
  stage: package
  only:
    - master
    - develop
    - merge_requests
  script:
    - mv build/app/outputs/apk/* ./exported/
  dependencies:
    - build
  artifacts:
    expire_in: 7 days
    paths:
      - exported

